[build]
    command = "npm run build"
    publish = "build/"
    functions = "netlify/functions"

[functions]
    external_node_modules = ["mongodb"]
    directory = "netlify/functions"
    node_bundler = "esbuild"
